config/routes.rb
  get   'gamification' => 'gamification#index' 
  get   'gamification/my_scores' => 'gamification#my_scores'
  get   'gamification/player/:player_id' => 'gamification#player', as: :gamification_player
  get   'gamification/actions' => 'gamification#actions'
  post  'gamification/actions/:action_id/play' => 'gamification#play_action', as: :gamification_action_play
  get   'gamification/configuration' => 'gamification#configuration'
  put   'gamification/configuration' => 'gamification#configuration_update', as: :gamification_configuration_update
  #post  'gamification/configuration' => 'gamification#configuration_update'

app/models/gamification/action_variable.rb
module Gamification
  #this is used for defining way how to fill Playlyfe Action variables before call to Playlyfe API
  class ActionVariable < ActiveRecord::Base
    self.table_name="gamification_action_variables"

    validate :av_validation

    scope :for_action, -> (action) { where(action_id: action.id) }

    def <=>(other_av)
      v= (self.action_id <=> other_av.action_id)
      if v == 0
        v= (self.variable <=> other_av.variable)
      else
        v  
      end  
    end 

    def should_be_saved?
      self.eval_string.to_s != ""
    end  

    private
  
      def av_validation
        a=Gamification.game.actions.find(self.action_id)
        if a.nil?
          self.errors.add(:action_id, I18n.t("gamification.action_variable.errors.action_was_not_found", action_id: self.action_id))
        else
          av=a.variables.detect {|v| self.variable == v["name"] }
          if av.nil?
            self.errors.add(:variable, I18n.t("gamification.action_variable.errors.variable_was_not_found", action_id: self.action_id, variable: variable))
          else
            if (self.eval_string.nil? || self.eval_string == "")
              self.errors.add(:eval_string, I18n.t("gamification.action_variable.errors.eval_string_is_empty", action_id: self.action_id, variable: variable, eval_string: eval_string))
            else
              [Issue.first, Issue.last].each do |issue|
                begin
                  result=eval(self.eval_string)
                rescue Exception => exc #there must be Exception catch, see http://stackoverflow.com/questions/542845/how-to-rescue-an-eval-in-ruby
                  self.errors.add(:eval_string, I18n.t("gamification.action_variable.errors.eval_string_is_wrong", action_id: self.action_id, variable: variable, eval_string: eval_string, issue_id: issue.id, ex_message: exc.message))                
                end  
                
                #eval is ok, but what about the result?
                if (av["type"] == "string" && !result.kind_of?(String)) || (av["type"] == "int" && !result.kind_of?(Integer) )
                  self.errors.add(:eval_string, I18n.t("gamification.action_variable.errors.eval_string_returning_wrong_type", action_id: self.action_id, variable: variable, eval_string: eval_string, issue_id: issue.id, type: av["type"], result: result))                
                end                
              end  
            end  

          end
        end

    end      

  end
end    

app/models/gamification/user_to_player.rb
module Gamification
  class UserToPlayer < ActiveRecord::Base
    self.table_name="gamification_users_to_players"
   
    belongs_to :user, class_name: User

    validate :validate_player_id
    validates :user, presence: true

    def player
      @player||=Gamification.game.players.find(self.player_id)
    end

    private
      def validate_player_id
        if self.player_id.blank? || !( (Gamification.game.players.to_a.collect {|p| p.id}).include?(self.player_id))
          self.errors.add(:player_id, I18n.t("gamification.user_to_player.errors.player_is_not_in_game", player_id: self.player_id) )
        end  
      end    
  end
end  



module PlaylyfeClient
  class Player 
    def users
      User.find(Gamification::UserToPlayer.where(player_id: self.id).pluck(:user_id))
    end
    
  end  
end    

app/controllers/gamification_controller.rb
class GamificationController < ApplicationController
  
  before_filter :require_player_or_admin 
  before_filter :require_admin, except: [:index, :my_scores]
  
  def index
    @player=User.current.player #can be nil for admin!

    if params[:refresh_game]
      Gamification.game=nil #this will force refresh, otherwise game is chached only play_action is doing requests to Playlyfe API
    end  
    load_actions_and_game_players
    load_teams
    load_leaderboards
  end
      
  def my_scores
    @player=User.current.player
    render "player"
  end

  #admin actions
    
  def player
    redirect_to gamification_url unless set_player
  end

  def actions
    load_actions_and_game_players
    @player=no_player
  end

  def play_action
    status= :ok
    if (set_player && set_action)
      begin
        @player.play(@action)
        flash[:notice] = t("gamification.play_action.action_successfully_played", action_id: @action.id, player_id: @player.id)
      rescue PlaylyfeClient::Error => e
        flash[:error] = e.message
        status= :unprocessable_entity
      end  
    end  
    
    load_actions_and_game_players
    @player=no_player if @player.blank?

    render "actions", status: status
  end

  def configuration
    load_actions_and_game_players
    
    @users_to_players=Gamification::UserToPlayer.all.to_a
    5.times { @users_to_players << Gamification::UserToPlayer.new }
    @users=User.order("login ASC")
    
    @available_event_ids=Gamification::EventToAction.available_event_ids
    @events_to_actions=Gamification::EventToAction.all
    5.times { @events_to_actions << Gamification::EventToAction.new }
    @actions_variables=get_action_variables(@actions.to_a.select {|a| !a.variables.empty?})
  end

  def configuration_update
    u2p_errors=[]
    e2a_errors=[]
        
    u2p_errors=update_users_to_players if params["users_to_players"].present?
    e2a_errors=update_events_to_actions if params["events_to_actions"].present?
    av_errors=update_action_variables(params["action_variables"])

    if u2p_errors.blank? && e2a_errors.blank? && av_errors.blank?
      flash[:notice]=I18n.t("gamification.configuration.successfully_updated")
    else
      flash[:error]=(u2p_errors+e2a_errors+av_errors).join("<br />")
    end  
    redirect_to gamification_configuration_url
  end  

  private

    def game
      begin
        @game||=Gamification.game
      rescue PlaylyfeClient::ConnectionError 
        flash[:error]="Your settings are not correct! No such client is recognized by Playlyfe.com"
        redirect_to plugin_settings_path(:redmine_gamification_playlyfe)
      end  
      @game
    end 
   
    def set_player
      @player=game.players.find(params[:player_id])
      if @player.blank?
        flash[:error] = t("gamification.user_to_player.errors.player_is_not_in_game", player_id: params[:player_id])
        return false
      else  
        return true
      end
    end   

    def set_action
      @action=game.actions.find(params[:action_id])
      if @action.blank?
        flash[:error] = t("gamification.event_to_action.errors.action_is_not_in_game", action_id: params[:action_id])
        return false
      else  
        return true
      end
    end  

    def require_player_or_admin
      return unless require_login
      game #to raise error if client cannot connect to Playlyfe game 
      if (User.current.admin? || User.current.player?)
        return true
      else  
        render_403
        return false
      end
    end

    def update_users_to_players
      errors=[]
      clean_u2ps=cleaned_u2ps.dup
      existing_u2ps=Gamification::UserToPlayer.all

      existing_u2ps.each do |ar_u2p|
        p_id=ar_u2p.player_id
        u_id=ar_u2p.user_id
        h={user_id: u_id, player_id: p_id}

        if clean_u2ps.include?(h)
          #no change here: leave it in DB, remove from params
          clean_u2ps.delete(h)
        else
          #is in DB but do not set in params => delete from DB
          ar_u2p.destroy
        end  
      end
      
      #there left only new records in clean_u2ps 
      clean_u2ps.each do |u_p|
        u2p=Gamification::UserToPlayer.new
        u2p.player_id=u_p[:player_id]
        u2p.user_id=u_p[:user_id]
        unless u2p.save
          errors << I18n.t("gamification.user_to_player.errors.error_on_creating", user_id: u2p.user_id, player_id: u2p.player_id, errors: u2p.errors.full_messages.join("; "))
        end 
      end
      errors
    end  

    def cleaned_u2ps
      u2ps=params[:users_to_players].select { |u2p| u2p[:user_id].to_i > 0 && (u2p[:player_id].present? && u2p[:player_id].to_s != "0") }
      u2ps.collect {|u2p| { user_id: u2p[:user_id].to_i, player_id: u2p[:player_id].to_s} }
    end    

    def update_events_to_actions
      errors=[]
      clean_e2as=cleaned_e2as.dup
      existing_e2as=Gamification::EventToAction.all

      existing_e2as.each do |ar_e2a|
        h={event_id: ar_e2a.event_id, action_id: ar_e2a.action_id}

        if clean_e2as.include?(h)
          #no change here: leave it in DB, remove from params
          clean_e2as.delete(h)
        else
          #is in DB but do not set in params => delete from DB
          ar_e2a.destroy
        end  
      end
      
      #there left only new records in clean_e2as 
      clean_e2as.each do |u_p|
        e2a=Gamification::EventToAction.new
        e2a.event_id=u_p[:event_id]
        e2a.action_id=u_p[:action_id]
        unless e2a.save
          errors << I18n.t("gamification.event_to_action.errors.error_on_creating", event_id: e2a.event_id, action_id: e2a.action_id, errors: e2a.errors.full_messages.join("; "))
        end  
      end
      errors
    end  

    def cleaned_e2as
      e2as=params[:events_to_actions].select { |e2a| e2a[:action_id].present? && e2a[:event_id].present? }
      e2as.collect {|e2a| { event_id: e2a[:event_id].to_s, action_id: e2a[:action_id].to_s} }
    end 

    def load_actions_and_game_players
      @actions||=game.actions
      @game_players||=game.players
    end  

    def load_teams
      @teams||=game.teams
    end  

    def load_leaderboards
      @leaderboards||=game.leaderboards
    end  

    def no_player
      ::PlaylyfeClient::V2::Player.new({id: 0, alias: "----"},game)
    end  

    def get_action_variables(actions)
      avs=Gamification::ActionVariable.order("action_id ASC, variable ASC").to_a
      actions.each do |action_with_variables| 
        action_with_variables.variables.each do |var| 
          stored_av=avs.detect {|av| av.action_id == action_with_variables.id && av.variable == var["name"]}
          if stored_av.nil?
            avs << Gamification::ActionVariable.new(action_id: action_with_variables.id, variable: var["name"], eval_string: '', required: var["required"])
          end  
        end
      end    
      avs.sort
    end  

     def update_action_variables(av_params)

      errors=[]
      return errors if av_params.blank?

      existing_avs=Gamification::ActionVariable.order("action_id ASC, variable ASC").to_a

      av_params.each_key do |action_id|
        av_params[action_id].keys.each do |variable|
          stored_av=existing_avs.detect {|av| av.action_id == action_id && av.variable == variable}
          
          if stored_av.nil?
            s_av= Gamification::ActionVariable.new(action_id: action_id, variable: variable, eval_string: av_params[action_id][variable])
          else  
            stored_av.eval_string= av_params[action_id][variable]
            s_av= stored_av
          end  
          
          if s_av.should_be_saved?
            unless s_av.save
              errors << I18n.t("gamification.action_variable.errors.error_on_save", action_id: action_id, variable: variable, eval_string: av_params[action_id][variable], errors: s_av.errors.full_messages.join("; "))
            end  
          end

        end
      end  

      errors
    end 

end  

app/helpers/gamification_helper.rb
module GamificationHelper
  def rewards_to_s_for_action(action)
    rewards=action.rewards.collect do |rwd|
      metric_name= rwd[:metric].name
      change_value=rwd[:value]
      change_to_s=(rwd[:verb] == "add" ? "+= #{change_value}" : (rwd[:verb] == "remove" ? "-= #{change_value}" : " = #{change_value}"))
      if  rwd[:probability].to_i != 1
        nil # we show only 100% rewards
      else  
        " #{metric_name} #{change_to_s} "
      end  
    end  

    rewards.compact
  end  

  def player_to_link(pl)
    if User.current.admin?
      plink=link_to( pl.name, gamification_player_url(player_id: pl.id))
    elsif User.current.player? && User.current.player.id == pl.id 
      plink=link_to(pl.name, gamification_my_scores_url)
    else
      plink=pl.name.html_safe
    end   
    plink+="<span class=\"states\"></span>".html_safe
    plink+="<span class=\"sets\"></span>".html_safe
    plink
  end       

  def all_users_for_player(player)
    Gamification::UserToPlayer.where(player_id: player.id).collect {|up| up.user.login}
  end 

  def options_for_user_select(user_id)
    options_for_select( ([["-not used-",0]]+ @users.to_a.collect {|u| ["#{u.login} (#{u.name})", u.id]}), user_id)
    #options_for_select([["one",1],["two",2]])
  end

  def options_for_player_select(player_id)
    options_for_select( ([["-not used-",0]]+ @game_players.to_a.collect {|p| ["#{p.id} (#{p.name})", p.id]}), player_id)
    #options_for_select([["one",1],["two",2]])
  end 

  def options_for_event_select(event_id)
    options_for_select( ([["-not used-","-"]]+ @available_event_ids.to_a.collect {|e_id| [e_id, e_id]}), (event_id || "") )
  end 

  def options_for_action_select(action_id)
    options_for_select( ([["-not used-",""]]+ @actions.to_a.collect {|a| [a.name, a.id]}), (action_id || "") )
  end 

  def show_team(team)
    content_tag(:li) do 
      concat content_tag(:span, class: "team_name") { team.name }
      concat (team.members.collect {|tm| tm.name}).join(", ")
    end
  end

  def show_position(pos, current_player)
    return "" if pos.blank? || !pos.kind_of?(Array)
    
    if pos.first[:entity].kind_of?(PlaylyfeClient::Team)
      show_position_for_teams(pos, current_player)
    else
      show_position_for_players(pos, current_player)
    end  
  end
  
  def show_position_for_players(pos, current_player)  
    entities=[]
    
    pos.each do |p|
      entity=p[:entity]
      entities << ( (current_player && (current_player.id == entity.id)) ? "<strong>#{entity.name}</strong>" : "#{entity.name}" )
    end
      
    score=pos.first[:score]
    "#{entities.join("; ")} [#{score}]".html_safe
  end  

  def show_position_for_teams(pos, current_player)
    entities=[]
    score=pos.first[:score]

    pos.each do |p|
      entity=p[:entity]
      e_name= "#{entity.name} [#{average_on_player(entity, score)}]"
      entities << ( (current_player && current_player.teams.collect {|t| t.id}.include?(entity.id)) ? "<strong>#{e_name}</strong>" : "#{e_name}" )
    end
    
    "#{entities.join("; ")} [#{score}]".html_safe
  end  

  def average_on_player(team, score)
    average=(team.members.size == 0 ? 0 : score.to_i/team.members.size)
    "#{t("gamification.scores.average_on_player")}: #{average}"
  end
    
  def admin_area &block
    if User.current.admin?
      yield
    end  
  end  

  def event_full_name(ev)
      str=ev.event+":"
      if ev.kind_of?(PlaylyfeClient::V2::PlayerEvent::Base)
       str+=" #{ev.action_name} #{ev.rule_name} #{ev.process_name}"
      elsif ev.kind_of?(PlaylyfeClient::V2::TeamEvent::Base)
        str+=" #{ev.team_name}"
      elsif ev.kind_of?(PlaylyfeClient::V2::ProcessEvent::Base)
        str+=" #{ev.process_name}"
      end  
      str
  end 


end

app/views/gamification/_actions_with_variables_fields.html.erb
  <div id="actions_with_variables">
    <h3><%= t("gamification.configuration.action_variables_assigments") %></h3>
    
    <table>
      <thead>
        <tr>
          <th><%= t("gamification.action_variable.action") %></td>
          <th><%= t("gamification.action_variable.variable") %></td>
          <th><%= t("gamification.action_variable.eval_string") %></td>
        </tr>
      </thead>
      <tbody>
      <% @actions_variables.each do |av| %>
        <tr>
          <td><%= av.action_id %>
          <td><%= av.variable %><%="*" if av.required?%></td>
          <td><%= text_field_tag("action_variables[#{av.action_id}][#{av.variable}]", av.eval_string) %></td>  
        </tr>    
      <% end %>
      </tbody>
    </table>
    * = <%= t("gamification.action_variable.required") %>
  </div>  

app/views/gamification/_event_to_actions_fields.html.erb
  <div id="events_to_actions">
    <table>
      <thead>
        <tr>
          <th><%= t("gamification.configuration.event_from_redmine") %></th>
          <th><%= t("gamification.configuration.action_to_play") %></th>
        </tr>
      </thead>
      <tbody>
      <% @events_to_actions.each do |e2a| %>
        <tr>
          <td>
            <%= select_tag("events_to_actions[][event_id]", options_for_event_select(e2a.event_id) ) %>
          </td>
          <td>
            <%= select_tag("events_to_actions[][action_id]", options_for_action_select(e2a.action_id) ) %>
          </td>  
        </tr>    
      <% end %>
      </tbody>
    </table>

    <%= t("gamification.configuration.more_blank_after_submit") %>
  </div>  

app/views/gamification/_events.html.erb
<ul>
  <% for ev in events.to_a.reverse %>
    <li class="event">
      <span class="event_time">[<%= format_time(ev.timestamp) %>]</span>
      <span class="event_name"><%= event_full_name(ev) %></span>
      <br />
      <% begin %>
        <span class="event_actor"><%= ev.actor_alias if show_actor %></span>      
        <ul class="event_changes">
        <% ev.changes.each do |ch| %>
          <li><%= ch[:metric].name%>: <%= ch[:delta][2].to_s %> <%= ch[:delta][0].to_s %> => <%= ch[:delta][1].to_s %></li>
        <% end %>
        </ul>
      <% rescue %>
          Error in parsing event
      <% end %>
    </li>
  <% end %>
</ul>  

app/views/gamification/_scores.html.erb
<div id="scores">
  <table class="framed">
    <thead>
      <tr>
        <th><%= t("gamification.scores.point_counts.header") %></th>
        <th><%= t("gamification.scores.sets.header") %></th>
        <th><%= t("gamification.scores.states.header") %></th>
        <th><%= t("gamification.scores.compounds.header") %></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td id="point_counts">
          <%= render partial: "scores_points", locals: {point_scores: scores[:points]} %>
        </td>
        <td id="sets">
          <%= render partial: "scores_sets", locals: {set_scores: scores[:sets]} %>
        </td>
        <td id="states">
          <%= render partial: "scores_states", locals: {state_scores: scores[:states]} %>
        </td>
        <td id="compounds">
          <%= render partial: "scores_compounds", locals: {compound_scores: scores[:compounds]} %>
        </td>                
      </tr>
    </tbody>  
  </table>  
</div>

app/views/gamification/_scores_compounds.html.erb
 <table class="framed_scores">
    <tbody>
      <% compound_scores.keys.sort.each do |key| %>
      <tr>
        <td class="metric_name"><%= key %>:</td>
        <td id="metric_value"><%= compound_scores[key] %></td>
      </tr>
     <% end %> 
    </tbody>  
  </table>

app/views/gamification/_scores_points.html.erb
 <table class="framed_scores">
    <tbody>
      <% point_scores.keys.sort.each do |key| %>
      <tr>
        <td class="metric_name"><%= key %>:</td>
        <td id="metric_value"><%= point_scores[key] %></td>
      </tr>
     <% end %> 
    </tbody>  
  </table>

app/views/gamification/_scores_sets.html.erb
 <table class="framed_scores">
    <tbody>
      <% set_scores.each_value do |items| %>
        <% items.each do |item| %>
          <tr>
            <td class="metric_name"><%= item[:name] %>:</td>
            <td id="metric_value"><%= item[:count] %>x</td>
          </tr>
        <%end%>
     <% end %> 
    </tbody>  
  </table>

app/views/gamification/_scores_states.html.erb
 <table class="framed_scores">
    <tbody>
      <% state_scores.keys.sort.each do |key| %>
      <tr>
        <td class="metric_name"><%= key %>:</td>
        <td id="metric_value"><%= state_scores[key] %></td>
      </tr>
     <% end %> 
    </tbody>  
  </table>

app/views/gamification/_shared_links.html.erb
<div id="shared_links">
  | 
<% admin_area do %>  
  <%= link_to(t("gamification.play_action.title"), gamification_actions_path) %> | 
  <%= link_to(t(:label_settings), gamification_configuration_path) %> | 
<% end %>
<%= link_to t("gamification.index.refresh_game"), gamification_url(refresh_game: 1) %> | 
</div>

app/views/gamification/_users_to_players_fields.html.erb
  <div id="users_to_players">
    <table>
      <thead>
        <tr>
          <th><%= t("gamification.configuration.user_from_redmine") %></th>
          <th><%= t("gamification.configuration.player_to_link") %></th>
        </tr>
      </thead>
      <tbody>
      <% @users_to_players.each do |u2p| %>
        <tr>
          <td>
            <%= select_tag("users_to_players[][user_id]", options_for_user_select(u2p.user_id) ) %>
          </td>
          <td>
            <%= select_tag("users_to_players[][player_id]", options_for_player_select(u2p.player_id) ) %>
          </td>  
        </tr>    
      <% end %>
      </tbody>
    </table>

    <%= t("gamification.configuration.more_blank_after_submit") %>
  </div>  

app/views/gamification/actions.html.erb
<%= stylesheet_link_tag '/gamification.css', plugin: 'redmine_gamification_playlyfe', media: 'screen' %>

<%= render partial: "shared_links" %>

<script>
function set_player_id_to_buttons($select){
  $(".gamification-action_button").find(".player_id").val($select.val());
};

</script>


<div>
  <%= link_to t("gamification.index.refresh_game"), gamification_url(refresh_game: 1) %>
</div>  

<div>
<%= label_tag(:player_id, t("gamification.play_action.choose_player")) %>
<%=   select_tag(:player_id, 
        options_for_select( ([["--",0]]+ @game_players.to_a.collect {|p| [p.name, p.id]}), @player.id),
        onchange: "set_player_id_to_buttons($(this))",
        id: "player"
        ) %>
</div>



<div>
  <h3><%= t("gamification.play_action.available_actions") %></h3>
<% for action in @actions.to_a do %>
  <%= form_tag(gamification_action_play_url(action_id: action.id), class: "gamification-action_button") do %>
    <%= hidden_field_tag(:player_id, 0, id: "#{action.id}_player", class: "player_id") %>
    <%= submit_tag(action.name) %>
  <% end %>
<% end %>
</div>

app/views/gamification/configuration.html.erb
<%= stylesheet_link_tag '/gamification.css', plugin: 'redmine_gamification_playlyfe', media: 'screen' %>

<%= render partial: "shared_links" %>

<h2><%= t("gamification.configuration.header") %></h2>

<div id="gamification">
<%= form_tag(gamification_configuration_update_url, method: :put) do %>

  <%= render partial: "event_to_actions_fields" %>  
  <%= render partial: "actions_with_variables_fields" %>  
  <%= render partial: "users_to_players_fields" %>

  <div class="actions">
    <%= submit_tag  t("gamification.configuration.save_configuration_button") %>
  </div>
<% end %>
</div>

app/views/gamification/index.html.erb
<%= stylesheet_link_tag '/gamification.css', plugin: 'redmine_gamification_playlyfe', media: 'screen' %>

<%= render partial: "shared_links" %>

<div id="game">
  
  <div class="left_column third_width">
      
    <div id="team_leaderboards">
      <% for lb in @leaderboards.for_teams.to_a do %>
        <%= render partial: "leaderboard", locals: {leaderboard: lb} %>
      <% end %>
    </div>

    <div id="teams">
      <h3><%= t("gamification.index.teams") %></h3>
      <ul>
      <% for team in @teams.to_a do %>
        <%= show_team(team) %>
      <% end %>
      </ul>
    </div>
  </div>

  <div class="left_column third_width">

    <div id="player_leaderboards">
      <% for lb in @leaderboards.for_players.to_a do %>
        <%= render partial: "leaderboard", locals: {leaderboard: lb} %>
      <% end %>
    </div>
    
    <div id="players">
      <h3><%= t("gamification.index.available_players") %></h3>
      <ul>
        <% for pl in @game_players.to_a do %>
          <li><%= player_to_link(pl) %></li>
        <% end %>
      </ul>
    </div>    
  </div>
 
  <div class="right_column  third_width">


    <div id="events">
      <h3><%= t("gamification.last_events.header") %></h3>
      <%= render partial: "events", locals: {events: @game.events(4.days.ago.utc, Time.now.utc), show_actor: true} %>
    </div>   
    
    <div id="actions">
      <h3><%= t("gamification.index.available_actions") %></h3>
      <ul>
      <% for action in @actions.to_a do %>
        <li><%= action.name %> <%= rewards_to_s_for_action(action) %></li>
      <% end %>
      </ul>
    </div>

  </div>  
</div>

app/views/gamification/player.html.erb
<%= stylesheet_link_tag '/gamification.css', plugin: 'redmine_gamification_playlyfe', media: 'screen' %>

<%= render partial: "shared_links" %>
<% puts("HERE1") %>
<div class="left_column">
  <h3><%= t("gamification.player.header", name: @player.name) %></h3>
  <div>
    <%= t("gamification.player.for_users") %>: <%= all_users_for_player(@player) %>
  </div>  
    <%= render partial: "scores", locals: {scores: @player.scores(true)} %>
</div>
<% puts("HERE2") %>
<div class="right_column">
  <div id="events">
  <h4><%= t("gamification.last_events.header") %></h4>
    <%= render partial: "events", locals: {events: @player.events(4.days.ago.utc, Time.now.utc), show_actor: false} %>
  </div>  
</div>
<% puts("HERE3") %>